/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventas.frame;

import com.ventas.entities.CategoriaIva;
import com.ventas.entities.Cliente;

import com.ventas.entities.Domicilio;
import com.ventas.entities.FormaPago;
import com.ventas.entities.Saldo;
import com.ventas.entities.TipoDoc;
import com.ventas.entities.Usuario;
import com.ventas.entities.Vendedor;
import com.ventas.services.ClienteService;
import com.ventas.services.TipoDocService;
import com.ventas.services.UsuarioService;
import com.ventas.services.VendedorService;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Mario Gianotti
 */
public class NuevoClienteFrame extends javax.swing.JFrame {

    private List<TipoDoc> tipos = null;
    private List<Vendedor> vendedores = null;
    private Usuario usuario;
    private final Integer nivel = 2;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private List<CategoriaIva> categorias;
    private List<FormaPago> formasPago;
//    private final Integer order_num;
//private final String order_name;

    /**
     * Creates new form NewJFrame
     */
    public NuevoClienteFrame() {
        initComponents();
//        this.order_name = order_name;
//this.order_num = order_num;
        limpiarCampos();
        llenarCombos();
        comboFormasPago.setSelectedIndex(1);//por defecto que sea el index 1
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        guardarNuevoClienteBtn = new javax.swing.JButton();
        volverNuevoClienteBtn = new javax.swing.JButton();
        codigoTxt = new javax.swing.JTextField();
        razonSocialTxt = new javax.swing.JTextField();
        cuitTxt = new javax.swing.JTextField();
        calleTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        celTxt = new javax.swing.JTextField();
        mailTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        obsTxt = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        numeroTxt = new javax.swing.JTextField();
        pisoTxt = new javax.swing.JTextField();
        localidadTxT = new javax.swing.JTextField();
        provinciaTxt = new javax.swing.JTextField();
        descuentoTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        codigoPostalTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        comboFormasPago = new javax.swing.JComboBox();
        comboCategoria = new javax.swing.JComboBox();
        llevaDescuentoChk = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        comboVendedores = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        entregaTxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        aliasTxt = new javax.swing.JTextField();

        jLabel28.setText("jLabel28");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("NUEVO CLIENTE");

        guardarNuevoClienteBtn.setText("Guardar");
        guardarNuevoClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarNuevoClienteBtnActionPerformed(evt);
            }
        });

        volverNuevoClienteBtn.setText("Volver");
        volverNuevoClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverNuevoClienteBtnActionPerformed(evt);
            }
        });

        codigoTxt.setText("Id");

        razonSocialTxt.setText("Razón Social");

        cuitTxt.setText("Cuit");

        calleTxt.setText("Domicilio");

        telTxt.setText("Teléfono");

        celTxt.setText("Celular");

        mailTxt.setText("Maiil");

        jLabel1.setText("Codigo:");

        jLabel2.setText("Razón Social");

        jLabel3.setText("Cuit");

        jLabel4.setText("Calle");

        jLabel5.setText("Categoria");

        jLabel6.setText("Telefono");

        jLabel7.setText("Celular");

        jLabel8.setText("Mail");

        jLabel9.setText("Observaciones");

        obsTxt.setColumns(20);
        obsTxt.setRows(5);
        jScrollPane2.setViewportView(obsTxt);

        jLabel10.setText("Numero");

        jLabel11.setText("Piso Dto.");

        jLabel13.setText("Localidad");

        jLabel14.setText("Provincia");

        numeroTxt.setText("Numero");

        pisoTxt.setText("Piso");

        localidadTxT.setText("Localidad");

        provinciaTxt.setText("Provincia");

        descuentoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        descuentoTxt.setText("Descuento");

        jLabel16.setText("Codigo Postal");

        codigoPostalTxt.setText("CODIGO POSTAL");

        jLabel17.setText("Forma de Pago");

        comboFormasPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        llevaDescuentoChk.setText("Lleva Descuento:");

        jLabel19.setText("*");

        jLabel20.setText("*");

        jLabel21.setText("*");

        jLabel22.setText("*");

        jLabel23.setText("*");

        jLabel24.setText("*");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel25.setText("*  Campos obligatorios para completar.");

        jLabel15.setText("Tipo:");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setText("*");

        jLabel27.setText("Vendedor:");

        comboVendedores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel26.setText("Entrega:");

        entregaTxt.setText("ENTREGA");

        jLabel29.setText("Alias:");

        aliasTxt.setText("ALIAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(guardarNuevoClienteBtn)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel29))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(volverNuevoClienteBtn)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aliasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entregaTxt)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel21))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(telTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                                                        .addComponent(celTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(mailTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel24))
                                                    .addComponent(codigoPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(cuitTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(localidadTxT, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                                            .addComponent(provinciaTxt)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel22)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addGap(165, 165, 165)
                                                                        .addComponent(jLabel18))
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel15)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addComponent(llevaDescuentoChk)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel17)
                                                                    .addComponent(descuentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jLabel27)
                                                                    .addComponent(comboVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(comboFormasPago, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jLabel23)))))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addContainerGap())
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20))
                                            .addComponent(pisoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 115, Short.MAX_VALUE))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel19)
                    .addComponent(jLabel2)
                    .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(aliasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(llevaDescuentoChk)
                    .addComponent(descuentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pisoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(localidadTxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFormasPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(codigoPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(provinciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(entregaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarNuevoClienteBtn)
                            .addComponent(volverNuevoClienteBtn))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarNuevoClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarNuevoClienteBtnActionPerformed
        if (habilitado()) {
            guardarCliente();
        }
    }//GEN-LAST:event_guardarNuevoClienteBtnActionPerformed

    private void volverNuevoClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverNuevoClienteBtnActionPerformed
        volver();

    }//GEN-LAST:event_volverNuevoClienteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aliasTxt;
    private javax.swing.JTextField calleTxt;
    private javax.swing.JTextField celTxt;
    private javax.swing.JTextField codigoPostalTxt;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JComboBox comboFormasPago;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JComboBox comboVendedores;
    private javax.swing.JTextField cuitTxt;
    private javax.swing.JTextField descuentoTxt;
    private javax.swing.JTextField entregaTxt;
    private javax.swing.JButton guardarNuevoClienteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox llevaDescuentoChk;
    private javax.swing.JTextField localidadTxT;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JTextArea obsTxt;
    private javax.swing.JTextField pisoTxt;
    private javax.swing.JTextField provinciaTxt;
    private javax.swing.JTextField razonSocialTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JButton volverNuevoClienteBtn;
    // End of variables declaration//GEN-END:variables

    private void guardarCliente() {
        if (validarCampos()) {
            Cliente cliente = new Cliente();
            Saldo saldo = new Saldo();
            int rowCategoria = comboCategoria.getSelectedIndex();
            int rowFormasPago = comboFormasPago.getSelectedIndex();
            int rowTipoDoc = comboTipo.getSelectedIndex();
            Integer codigo = Integer.valueOf(codigoTxt.getText());
            CategoriaIva categoria = categorias.get(rowCategoria - 1);
            FormaPago formas = formasPago.get(rowFormasPago - 1);
            TipoDoc tipoDoc = tipos.get(rowTipoDoc -1);
            cliente.setRazonSocial(razonSocialTxt.getText());
            cliente.setCodigo(codigo);
            cliente.setAlias(aliasTxt.getText());
            saldo.setSaldo(0.0);
            cliente.setCuit(cuitTxt.getText());
            cliente.setCategoriaDeIva(categoria);
            cliente.setTelefono(telTxt.getText());
            cliente.setCelular(celTxt.getText());
            cliente.setMail(mailTxt.getText());
            cliente.setObservaciones(obsTxt.getText());
            cliente.setFormaPago(formas);
            cliente.setVendedor(vendedores.get(comboVendedores.getSelectedIndex() - 1));
            if (llevaDescuentoChk.isSelected()) {
                cliente.setTieneDescuento(true);
                cliente.setDescuento(Float.valueOf(descuentoTxt.getText().replace(",", ".")));
            } else {
                cliente.setTieneDescuento(false);
                cliente.setDescuento(0F);
            }
            cliente.setActivo(true);
            if (entregaTxt.getText().isEmpty()) {
                cliente.setEntrega("");
            } else {
                cliente.setEntrega(entregaTxt.getText());
            }
            // Armar la direccion
            Domicilio domicilio = new Domicilio();
            domicilio.setCalle(calleTxt.getText());
            domicilio.setNumero(numeroTxt.getText());
            domicilio.setPisoDto(pisoTxt.getText());
//            domicilio.setDepartamento(departamentoTxt.getText());
            domicilio.setLocalidad(localidadTxT.getText());
            domicilio.setProvincia(provinciaTxt.getText());
            domicilio.setCodigoPostal(codigoPostalTxt.getText());

            cliente.setDomicilio(domicilio);
            cliente.setTipoDoc(tipoDoc);
            try {
                new ClienteService().saveCliente(cliente);
                JOptionPane.showMessageDialog(this, "CLIENTE guardado correctamente.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar CLIENTE.");
                return;
            }
//            ClienteTraba ct = new ClienteTraba();
//            ct.setCodigo(codigoTxt.getText());
//            ct.setTraba1(false);
//            try {
//                new ClienteTrabaService().saveCliente(ct);
//            } catch (Exception ex) {
//                Logger.getLogger(NuevoClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            CustomerTraba cuTr = new CustomerTraba();
//            cuTr.setCodigo(codigoTxt.getText());
//            cuTr.setTraba2(false);
//            try {
//                new CustomerTrabaService().saveCliente(cuTr);
//            } catch (Exception ex) {
//                Logger.getLogger(NuevoClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
            limpiarCampos();
            llenarCombos();
            comboFormasPago.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(this, "CLIENTE Verifique datos obligatorios.");
        }
    }

    private void limpiarCampos() {
        codigoTxt.setText("");
        aliasTxt.setText("");
        celTxt.setText("");
        cuitTxt.setText("");
        calleTxt.setText("");
        numeroTxt.setText("");
        pisoTxt.setText("");
        localidadTxT.setText("");
        provinciaTxt.setText("");
        razonSocialTxt.setText("");
        llevaDescuentoChk.setSelected(false);
        telTxt.setText("");
        mailTxt.setText("");
        obsTxt.setText("");
        descuentoTxt.setText("0.0");
        codigoPostalTxt.setText("");
        comboCategoria.removeAllItems();
        comboCategoria.addItem("");
        comboFormasPago.removeAllItems();
        comboFormasPago.addItem("");
        comboTipo.removeAllItems();
        comboTipo.addItem("");
        comboVendedores.removeAllItems();
        comboVendedores.addItem("");
        entregaTxt.setText("");
    }

    private boolean validarCampos() {
        int row = comboVendedores.getSelectedIndex();
        if (row < 1) {
            JOptionPane.showMessageDialog(this, "Debe asignar un Vendedor al Cliente");
            return false;
        }
        if (codigoTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "CLIENTE - Verifique el Codigo.");
            return false;
        }
        if (!verificarExiste()) {
            JOptionPane.showMessageDialog(this, "CLIENTE - Código duplicado.");
            codigoTxt.requestFocus();
            return false;
        }
        if (numeroTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "CLIENTE - Ingrese un Número.");
            return false;
        }
        if (razonSocialTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Cliente - Verifique la razon social.");
            return false;
        }

        if (comboFormasPago.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Cliente - Seleccione la forma de pago del cliente");
        }
        if (calleTxt.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Cliente - Complete la calle");
            return false;
        }
//        if (cuitTxt.getText().length() != 13) {
//            if (tipos.get(comboTipo.getSelectedIndex() - 1).getCodigo() != "96" || tipos.get(comboTipo.getSelectedIndex() - 1).getCodigo() != "99") {
//                JOptionPane.showMessageDialog(this, "CLIENTE - Verifique la CUIT lleva guiones.");
//                cuitTxt.requestFocus();
//                return false;
//            }
//        }
        if (comboCategoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Cliente - Seleccione la categoria del cliente");
            return false;
        }
        if (comboTipo.getSelectedIndex() < 1) {
            JOptionPane.showMessageDialog(this, "Cliente - Seleccione Tipo de CUIT");
            return false;
        }
        return true;
    }

    private void llenarCombos() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) comboCategoria.getModel();

//        model.addElement("1- Inscripto");
//        model.addElement("2- Monotributo");
//        model.addElement("3- Exento");
//        model.addElement("4- Consumidor Final");

//        DefaultComboBoxModel model2 = (DefaultComboBoxModel) comboFormasPago.getModel();

//        model2.addElement("1- Contado");
//        model2.addElement("2- 7 dias fecha factura");
//        model2.addElement("3- 14-dias fecha factura");
//        model2.addElement("4- otro");

//        comboCategoria.setModel(model);
//        comboFormasPago.setModel(model2);

        tipos = null;
        try {
            tipos = new TipoDocService().getAllTipoDocs();
        } catch (Exception ex) {
//            Logger.getLogger(NuevoClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        if (tipos != null && !tipos.isEmpty()) {
            for (TipoDoc tipo : tipos) {
                comboTipo.addItem(tipo.getNombre());
            }
        }

        vendedores = null;
        try {
            vendedores = new VendedorService().getAllVendedors();
        } catch (Exception ex) {
//            Logger.getLogger(NuevoClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        comboVendedores.removeAllItems();
        comboVendedores.addItem("");
        if (vendedores != null && !vendedores.isEmpty()) {
            for (Vendedor ve : vendedores) {
                comboVendedores.addItem(ve.getNombre());
            }
        }
    }

    private boolean verificarExiste() {
        Cliente ccl;
        Integer codigo = Integer.valueOf(codigoTxt.getText());
        try {
            ccl = new ClienteService().getClienteByCodigo(codigo);
        } catch (Exception ex) {
//            Logger.getLogger(NuevoClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "ERROR 769 - POSIBLE PERDIDA DE CONEXION CON SERVIDOR");
            return false;
        }
        if (ccl != null) {
            return false;
        } else {
            return true;
        }
    }

    private boolean habilitado() {
//        FileReader fr = null;
//        try {
//            fr = new FileReader("c:/ventas/permisos.txt");
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        BufferedReader br = new BufferedReader(fr);
//        String acceso = "";
//        try {
//            acceso = br.readLine();
//        } catch (IOException ex) {
//            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            br.close();
//        } catch (IOException ex) {
//            Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (acceso.equals("1")) {
            return true;
//        }
//        habilitar();
//        if (usuario != null) {
//            return true;
//        } else {
//            return false;
//        }
    }

    private void habilitar() {
//        usuario = null;
//        JTextField field = new JTextField("");
//        String[] options = {"Ingresar"};
//        int result = JOptionPane.showOptionDialog(
//                null,
//                field,
//                "Autorización de USUARIO",
//                JOptionPane.OK_CANCEL_OPTION,
//                JOptionPane.QUESTION_MESSAGE,
//                null,
//                options,
//                0);
//        if (field.getText().isEmpty()) {
//            usuario = null;
//            return;
//        }
//        switch (result) {
//            case 0:
//                int cod = Integer.valueOf(field.getText());
//                try {
//                    usuario = new UsuarioService().getUsuarioByCodigo(cod);
//                } catch (Exception ex) {
//                    Logger.getLogger(ModificarClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                if (usuario != null) {
//                    if (usuario.getActivo()) {
//                        JPasswordField field2 = new JPasswordField("");
//                        String[] opts = {"Ingresar"};
//                        int resulta = JOptionPane.showOptionDialog(
//                                null,
//                                field2,
//                                "CONTRASEÑA: " + usuario.getNombre() + ", Autorización",
//                                JOptionPane.OK_CANCEL_OPTION,
//                                JOptionPane.QUESTION_MESSAGE,
//                                null,
//                                opts,
//                                0);
//                        switch (resulta) {
//                            case 0:
//                                int contra = Integer.valueOf(new String(field2.getPassword()));
//                                if (contra == usuario.getContrasena()) {
//                                    if (usuario.getNivel() > nivel) {
//                                        JOptionPane.showMessageDialog(this, "Usuario no Habilitado");
//                                        usuario = null;
//                                    } else {
//                                        String f1 = sdf.format(usuario.getFecha());
//                                        String f2 = sdf.format(new Date());
//                                        if (usuario.getNivel() == 2) {
//                                            if (!f1.equals(f2)) {
//                                                JOptionPane.showMessageDialog(this, "Permiso de Usuario Vencido");
//                                                usuario = null;
//                                            }
//                                        }
//                                    }
//                                } else {
//                                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
//                                    usuario = null;
//                                }
//                                break;
//                        }
//                    } else {
//                        JOptionPane.showMessageDialog(this, "USUARIO Inactivo");
//                        usuario = null;
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(this, "No existe el Usuario");
//                    usuario = null;
//                }
//                break;
//        }
    }

    private void volver() {
        AbmClientesFrame abmClienteFrame = new AbmClientesFrame();
        abmClienteFrame.setVisible(true);
        this.dispose();
    }
}
