/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventas.frame;

import com.ventas.entities.Producto;
import com.ventas.entities.ProductoPrecio;
import com.ventas.services.ProductoService;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class ProductoNuevoFrame extends javax.swing.JFrame {

    private Producto producto;
    private ProductoPrecio precio;
    private DecimalFormat df = new DecimalFormat("#0.00");

    /**
     * Creates new form ProductoEditarFrame
     *
     * @param producto
     */
    public ProductoNuevoFrame() {
        initComponents();
        this.producto = producto;
        getContentPane().setBackground(new java.awt.Color(100, 100, 255));
        this.setLocationRelativeTo(null);
        limpiarCampos(producto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        detalleTxt = new javax.swing.JTextField();
        activoChk = new javax.swing.JCheckBox();
        costoTxt = new javax.swing.JTextField();
        lista1Txt = new javax.swing.JTextField();
        lista2Txt = new javax.swing.JTextField();
        lista3Txt = new javax.swing.JTextField();
        volverBtn = new javax.swing.JButton();
        grabarBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        impuestoTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR PRODUCTO");

        jLabel1.setText("Código:");

        jLabel2.setText("Detalle:");

        jLabel3.setText("Costo:");

        jLabel4.setText("Lista 1:");

        jLabel5.setText("Lista 2:");

        jLabel6.setText("Lista 3:");

        codigoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codigoTxt.setText("CODIGO");

        detalleTxt.setText("DETALLE");

        activoChk.setText("Activo");

        costoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        costoTxt.setText("COSTO");

        lista1Txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lista1Txt.setText("LISTA 1");

        lista2Txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lista2Txt.setText("LISTA 2");

        lista3Txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lista3Txt.setText("LISTA 3");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        grabarBtn.setText("Grabar");
        grabarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("IMPUESTO:");

        impuestoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        impuestoTxt.setText("IMPUESTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(grabarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(activoChk))
                                .addComponent(detalleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(costoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lista1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lista2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(impuestoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lista3Txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activoChk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(detalleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(costoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lista1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lista2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lista3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(impuestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(grabarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void grabarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarBtnActionPerformed
        grabar();
    }//GEN-LAST:event_grabarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoNuevoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoNuevoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoNuevoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoNuevoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoNuevoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activoChk;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JTextField costoTxt;
    private javax.swing.JTextField detalleTxt;
    private javax.swing.JButton grabarBtn;
    private javax.swing.JTextField impuestoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lista1Txt;
    private javax.swing.JTextField lista2Txt;
    private javax.swing.JTextField lista3Txt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos(Producto p) {
        codigoTxt.setText("");
        precio = p.getPrecio();
        Integer codigo = 0;
        codigo = new ProductoService().getRubroByCodigo(codigo);|
//        codigoTxt.setEditable(false);
        detalleTxt.setText("");
        detalleTxt.requestFocus();
        if (p.getActivo()) {
            activoChk.setSelected(true);
        } else {
            activoChk.setSelected(false);
        }
        if (p.getCosto() != null) {
            costoTxt.setText(df.format(p.getCosto()));
        } else {
            costoTxt.setText("0.00");
        }
        if (p.getLista1() != null) {
            lista1Txt.setText(df.format(p.getLista1()));
        } else {
            lista1Txt.setText("0.00");
        }
        if (p.getLista2() != null) {
            lista2Txt.setText(df.format(p.getLista2()));
        } else {
            lista2Txt.setText("0.00");
        }
        if (p.getLista3() != null) {
            lista3Txt.setText(df.format(p.getLista3()));
        } else {
            lista3Txt.setText("0.00");
        }
        if (p.getPrecio() != null) {
            precioTxt.setText(df.format(p.getPrecio()));
        } else {
            precioTxt.setText("0.00");
        }
        if (p.getImpuesto() != null) {
            impuestoTxt.setText(df.format(p.getImpuesto()));
        } else {
            impuestoTxt.setText("0.00");
        }
        precioTxt.setEditable(false);
        impuestoTxt.setEditable(false);
    }

    private void volver() {
        ProductosAbmFrame pmf = new ProductosAbmFrame();
        pmf.setVisible(true);
        this.dispose();
    }

    private void grabar() {
        if (validar()) {
            producto.setDetalle(detalleTxt.getText());
            Double co;
            Double p1;
            Double p2;
            Double p3;
            try {
                co = Double.valueOf(costoTxt.getText().replace(",", "."));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "ERROR Nro. 270 - COSTO INVALIDO");
                costoTxt.requestFocus();
                return;
            }
            producto.setCosto(co);
            try {
                p1 = Double.valueOf(lista1Txt.getText().replace(",", "."));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "ERROR Nro. 278 - LISTA 1 INVALIDO");
                lista1Txt.requestFocus();
                return;
            }
            producto.setLista1(p1);
            try {
                p2 = Double.valueOf(lista2Txt.getText().replace(",", "."));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "ERROR Nro. 289 - LISTA 2 INVALIDO");
                lista2Txt.requestFocus();
                return;
            }
            producto.setLista2(p2);
            try {
                p3 = Double.valueOf(lista3Txt.getText().replace(",", "."));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "ERROR Nro. 328 - LISTA 3 INVALIDO");
                lista3Txt.requestFocus();
                return;
            }
            producto.setLista3(p3);
            if (activoChk.isSelected()) {
                producto.setInactivo(false);
            } else {
                producto.setInactivo(true);
            }
            try {
                new ProductoService().updateProducto(producto);
            } catch (Exception ex) {
                Logger.getLogger(ProductoNuevoFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR Nro. 305 - GRABANDO PRODUCTO");
                return;
            }
            JOptionPane.showMessageDialog(this, "PRODUCTO ACTUALIZADO CORRECTAMENTE");
            volver();
        }
    }

    private boolean validar() {
        if (producto == null) {
            JOptionPane.showMessageDialog(this, "ERROR Nro. 341 - PRODUCTO INVALIDO");
            detalleTxt.requestFocus();
            return false;
        }
        if (costoTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ERROR Nro. 304 - COSTO INVALIDO");
            costoTxt.requestFocus();
            return false;
        }
        if (lista1Txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ERROR Nro. 327 - LISTA 1 INVALIDO");
            lista1Txt.requestFocus();
            return false;
        }
        if (lista2Txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ERROR Nro. 332 - LISTA 2 INVALIDO");
            lista2Txt.requestFocus();
            return false;
        }
        if (lista3Txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ERROR Nro. 328 - LISTA 3 INVALIDO");
            lista3Txt.requestFocus();
            return false;
        }
        if (precioTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ERROR Nro. 337 - LISTA 3 INVALIDO");
            lista3Txt.requestFocus();
            return false;
        }
        if (impuestoTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ERROR Nro. 337 - LISTA 3 INVALIDO");
            lista3Txt.requestFocus();
            return false;
        }
        return true;
    }
}
